version: "3.2"
services:
  www:
    build: .
    ports:
      - "6000:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - mysql
    networks:
      - default
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://recipe.toifatululum.com/pma/
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 6001:80
